### ISSUE TITLE
Failed to load schema

### ISSUE THREAD

**Issue by zolzaya** [vendure-ecommerce/storefront-remix-starter#16]
Hello,

When I run `npm  run generate` command I get following errors.
```
> generate
> graphql-codegen --config codegen.yml

✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate app/generated/graphql.ts
    ✖ Failed to load schema
    ◼ Load GraphQL documents
    ◼ Generate
  ❯ Generate app/generated/schema.graphql
    ✖ Failed to load schema
    ◼ Load GraphQL documents
    ◼ Generate
```

I didn't change anything in `app/providers`. I only upgraded packages. So how can I resolve it?

**Comment by michaelbromley** [comment]
Hi,

This is probably because the codegen script expects a Vendure server instance to be running at `http://localhost:3001`. I just pushed a commit that will now read the schema from an online demo instance so you don't need to have a local server running. Pull these changes and see if that works now.
