### ISSUE TITLE
Cloudflare Pages deployment - accesing environment variable `API_URL`

### ISSUE THREAD

**Issue by gnimmelf** [vendure-ecommerce/storefront-remix-starter#3]
Setting .env `API_URL` works in local development, but the same accessing mechanism, `process.env`, doesn't work on Cloudflare Pages deployment.

The environment variables are set in CF build settings, and I've tried with both `build` and `build:cf` without any luck. Googling gave me little, apart from that CF need special treatment due to CF Workers running V8, and not Node.

Not sure if this is on my end entierly, but tought I'd issue it as I am affected =)

Cheers,
Flemming

Edit: It's explained here https://remix.run/docs/en/v1/guides/envvars

**Comment by michaelbromley** [comment]
ah good find! I also ran into this and due to lack of time I just had to hard-code. So from reading that linked doc, it looks like we'd need a `wranagler.toml` with something like 

```toml
[env.production.vars]
VENDURE_API_URL = "https://my-shop.com/shop-api"
``` 

and then in then here https://github.com/vendure-ecommerce/storefront-remix-starter/blob/7b3079122b93140e5dd20be1303387c405e2a902/app/graphqlWrapper.ts#L5-L9

we'd want something like

```ts
const API_URL = typeof process !== 'undefined' 
         ? process.env.VENDURE_API_URL ?? DEMO_API_URL
         ? typeof VENDURE_API_URL !== 'undefined' ? VENDURE_API_URL  ?? DEMO_API_URL
         : DEMO_API_URL;
```

is that how you read it?

**Comment by gnimmelf** [comment]
There's more info here:
https://github.com/remix-run/remix/issues/1186#issuecomment-1018088856
https://github.com/remix-run/remix/issues/1186#issuecomment-1019492493

**Comment by suaterken** [comment]
Running into the same issue, any updates?

**Comment by patnir** [comment]
Why is this closed? I'm running into the same issue. @michaelbromley 's solution doesn't work.

**Comment by michaelbromley** [comment]
Hi @patnir, this solution does work, at least for what I needed in this demo.

**Comment by emt-mocha** [comment]
Instead of using ".env" for enviroment-variables,  use "**.dev.vars**" and place the the file in root directory. You may use loader function to fetch the variable:

`    export const loader = async ({context})=>{
   const variable = context.ENVIRONMENT_VARIABLE;
 return json()
}; `

Works in remix cloudflare pages.

**Comment by yonnic** [comment]
is there some alternative of .dev.vars which can be used in production ?
i need different env variables for different branches pushed with my code
