### ISSUE TITLE
Mixed content load issue

### ISSUE THREAD

**Issue by blackyzero** [vendure-ecommerce/storefront-remix-starter#7]
Hello,

Another issue with mixed content loading from browser.
```
VENDURE_API_URL=https://api-store.abc.com/shop-api
NODE_ENV=development
```

Although it's set as https, but most of images are being loaded via "http://api-store.abc.com/"

Any idea how to fix it?

Thank you.

**Comment by kyunal** [comment]
This isn't an issue caused by the storefront, but your vendure backend. It responds with asset URLs that are not HTTPS and the storefront just applies them.

To fix it, set the `assetUrlPrefix` option in the [AssetServerOptions](https://www.vendure.io/docs/typescript-api/asset-server-plugin/asset-server-options) that you pass to the plugin on `AssetServerPlugin.init()` according to your needs.
Example:
```typescript
// vendure-config.ts
AssetServerPlugin.init({
            route: 'assets',
            assetUrlPrefix: 'https://api-store.abc.com/assets/',
            ...
 }),
```

**Comment by blackyzero** [comment]
yeah, that fix my issue.
Thanks a lot @kyunal

**Comment by michaelbromley** [comment]
Thanks @kyunal for your help :)
